# Generated by Django 4.2.3 on 2023-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
